version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: score-view-portal-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 3147 # Đổi mật khẩu này trong môi trường production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kma-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: score-view-portal-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 3147 # Phải trùng với mật khẩu ở trên
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - kma-network

networks:
  kma-network:
    driver: bridge

volumes:
  postgres_data: