// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgicmduqfgcigtzxjjqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaWNtZHVxZmdjaWd0enhqanFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjU3NjMsImV4cCI6MjA2NTU0MTc2M30.wMQwzX8zL4RtiQpPR_O4ejJT5U-uusOE06awLsEYpSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);